// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccvahojhqurgprlhhyzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjdmFob2pocXVyZ3BybGhoeXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDIyMjAsImV4cCI6MjA2MjYxODIyMH0.2ncR8MAb_sYujpmTy5En62fEEmq4PlsQn1YAj5dndBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);